### ISSUE TITLE
How do i get past step 11.

### ISSUE THREAD

**Issue by chipillin** [OpenDroneMap/odm_vagrant#12]
Whenever I try to install Open Drone Map using ./install.sh i receive the error message no such file or depository. Please help.

**Comment by Fire5Earth** [comment]
Yea, I'm on the same problem. I used "tree" and "ls -R" commands to find it in the directory but no luck. Any thoughts?

**Comment by smathermather** [comment]
@dakotabenjamin -- are you seeing these q's?

**Comment by dakotabenjamin** [comment]
@smathermather nope. I'll turn on notifications. 

Hi folks. ODM has some huge updates we just pushed. Please head on over to the main [ODM](https://github.com/opendronemap/opendronemap) repository and look at the README for new install instructions. Make sure you're on the master branch and run git pull:

```
git checkout master
git pull origin master
```

**Comment by dakotabenjamin** [comment]
OK the readme has been fixed, you should be able to follow it without error.

**Comment by Fire5Earth** [comment]
Awesome. Thank you.
