### ISSUE TITLE
Ubuntu in Virtual Box stuck at login

### ISSUE THREAD

**Issue by abdulhaseeb292** [OpenDroneMap/odm_vagrant#14]
Hi, I am stuck at the login and pwd of ubuntu in VM and it keeps on looping. Can you please tell me how to get rid of it?

**Comment by dakotabenjamin** [comment]
Can you copy/paste the text of the issue or attach a screenshot?

Please also post in detail the steps you followed to get to this point.

**Comment by abdulhaseeb292** [comment]
I followed all the steps up-till step number 8, however there is no response after I enter the command "vagrant ssh". The VM however runs after "vagrant up" but the password can not be typed there. And it gives login error and keeps on looping. I am running it on host Windows 10. Please find the screen shots attached. 
![screenshot 2016-06-28 20 16 05](https://cloud.githubusercontent.com/assets/20181953/16421313/fb87c088-3d6d-11e6-9f8f-2917120dc26f.png)
![screenshot 2016-06-28 20 16 46](https://cloud.githubusercontent.com/assets/20181953/16421314/fb8b2a52-3d6d-11e6-800b-66380d5cc3b1.png)
![screenshot 2016-06-28 20 18 16](https://cloud.githubusercontent.com/assets/20181953/16421315/fb8deaf8-3d6d-11e6-9503-db704ff21243.png)

**Comment by dakotabenjamin** [comment]
When you type the password in, it will not show it to you, just type it in and press enter. 

However, your username should be "vagrant" and then it will not require a password.

**Comment by abdulhaseeb292** [comment]
I have already tried that, but it still gives the same error.
![screenshot 2016-06-28 21 04 22](https://cloud.githubusercontent.com/assets/20181953/16423072/0c5f5398-3d74-11e6-8042-40b6ec6ca1ce.png)

**Comment by dakotabenjamin** [comment]
Have you tried the password "vagrant"?

**Comment by abdulhaseeb292** [comment]
Just tried it and it works. Thanks a lot. 
![screenshot 2016-06-28 21 14 36](https://cloud.githubusercontent.com/assets/20181953/16423438/71bb90d4-3d75-11e6-97b4-f8e2996fe43d.png)
