### ISSUE TITLE
module named ecto

### ISSUE THREAD

**Issue by cristianmenghi** [OpenDroneMap/odm_vagrant#18]
Hi, im recently installed the software, when im tried to run it i got this error.
ImportError: No module named ecto

Ubuntu trusty 64bits.

**Comment by dakotabenjamin** [comment]
Can you give more information? What commands did you run? Did you run into any installation errors?

**Comment by cristianmenghi** [comment]
Sorry, my mistake.

**Comment by dakotabenjamin** [comment]
No worries, glad you got it fixed
