### ISSUE TITLE
Broken processing of external libraries (e.g. ecto)?

### ISSUE THREAD

**Issue by AZOM** [OpenDroneMap/odm_vagrant#22]
I was trying to build ODM when I stumbled over following:

> Linking CXX shared library ../../lib/libopencv_core.so
CMake Error: cmake_symlink_library: System Error: Protocol error
CMake Error: cmake_symlink_library: System Error: Protocol error
make[5]: *** [lib/libopencv_core.so.2.4.11] Error 1
make[4]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [opencv/stamp/opencv-build] Error 2
make[1]: *** [CMakeFiles/opencv.dir/all] Error 2
make: *** [all] Error 2
Compiling build
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at modules/odm_georef/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "PCL" (requested
  version 1.7) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

 > Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

>CMake Error at modules/odm_georef/CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

>  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

>-- Configuring incomplete, errors occurred!
See also "/vagrant_data/odm_app/OpenDroneMap/build/CMakeFiles/CMakeOutput.log".
Configuration Finished
vagrant@vagrant-ubuntu-trusty-64:/vagrant_data/odm_app/OpenDroneMap$

---

So I checked what went wrong in the logs and found this:

>CMake Error at /vagrant_data/odm_app/OpenDroneMap/SuperBuild/build/opencv/stamp/download-opencv.cmake:27 (message):
  error: downloading 'https://github.com/Itseez/opencv/archive/2.4.11.zip'
  failed

 >   status_code: 56
    status_string: "Failure when receiving data from the peer"
    log: Hostname was NOT found in DNS cache
    Trying 192.30.253.112...

>  Connected to github.com (192.30.253.112) port 443 (#0)

 > successfully set certificate verify locations:

>    CAfile: none
>    CApath: /etc/ssl/certs

 > SSLv3, TLS handshake, Client hello (1):

>make[2]: *** [opencv/stamp/opencv-download] Error 1
make[1]: *** [CMakeFiles/opencv.dir/all] Error 2

I am now verifying whether this is a firewall issue on my side or what else could cause the error?

Ah and by the way, the step 11) was also not really accurate for me. I had to type:
_bash configure.sh **install**_ (with the addition of "install") to make it run. And the paths are mostly slightly confusing because they always start with a "/" even if you don't give the full path from root... either change it to "./<path>" or omit the slashes in the beginning ;-)

**Comment by AZOM** [comment]
Haha fun fact: If I click on the link to the opencv-zip from here within the browser it works - but not in the script... o_0

**Comment by dakotabenjamin** [comment]
Yeah, sorry we've updated the UI for OpenDroneMap and forgot to document the changes here. 

Can you `wget https://github.com/Itseez/opencv/archive/2.4.11.zip` from the vagrant guest?

**Comment by AZOM** [comment]
@dakotabenjamin yes that works...

>vagrant@vagrant-ubuntu-trusty-64:/vagrant_data/odm_app/OpenDroneMap$ `wget https://github.com/Itseez/opencv/archive/2.4.11.zip`
--2017-05-22 12:39:01--  https://github.com/Itseez/opencv/archive/2.4.11.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/opencv/opencv/archive/2.4.11.zip [following]
--2017-05-22 12:39:03--  https://github.com/opencv/opencv/archive/2.4.11.zip
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/opencv/opencv/zip/2.4.11 [following]
--2017-05-22 12:39:03--  https://codeload.github.com/opencv/opencv/zip/2.4.11
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 91671436 (87M) [application/zip]
Saving to: ‘2.4.11.zip’

But it seems like it gets re-directed. Maybe the configure script cannot handle that?

**Comment by dakotabenjamin** [comment]
Maybe it timed out? Can you try to run `bash configure.sh reinstall`

**Comment by AZOM** [comment]
@dakotabenjamin It is running `reinstall`... but I saw that this "broken" links also happen in other places, for example:

>vagrant@vagrant-ubuntu-trusty-64:/vagrant_data/odm_app/OpenDroneMap$ `wget https://github.com/PDAL/PDAL/archive/aea5bb0cacc64b91d626eff491fbdbb5668c06d7.tar.gz`
--2017-05-22 12:54:56--  https://github.com/PDAL/PDAL/archive/aea5bb0cacc64b91d626eff491fbdbb5668c06d7.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/PDAL/PDAL/tar.gz/aea5bb0cacc64b91d626eff491fbdbb5668c06d7 [following]
--2017-05-22 12:54:58--  https://codeload.github.com/PDAL/PDAL/tar.gz/aea5bb0cacc64b91d626eff491fbdbb5668c06d7
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘aea5bb0cacc64b91d626eff491fbdbb5668c06d7.tar.gz’

---

>vagrant@vagrant-ubuntu-trusty-64:/vagrant_data/odm_app/OpenDroneMap/SuperBuild/download$ `wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz`
--2017-05-22 13:56:34--  https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/PointCloudLibrary/pcl/tar.gz/pcl-1.7.2 [following]
--2017-05-22 13:56:34--  https://codeload.github.com/PointCloudLibrary/pcl/tar.gz/pcl-1.7.2
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘pcl-1.7.2.tar.gz.1’

>    [                                     <=>                                                       ] 63,474,627  7.86MB/s   in 7.5s

>2017-05-22 13:56:43 (8.06 MB/s) - ‘pcl-1.7.2.tar.gz.1’ saved [63474627]

**Comment by dakotabenjamin** [comment]
302 is a redirection code, it looks like it was successful

**Comment by AZOM** [comment]
@dakotabenjamin yeah but only if I get it manually with `wget`... still waiting on the result of the script

**Edit:**
Here is the result:

>Install the project...
-- Install configuration: "Release"
-- Installing: /vagrant_data/odm_app/OpenDroneMap/SuperBuild/install/lib/libtex.a
-- Installing: /vagrant_data/odm_app/OpenDroneMap/SuperBuild/install/bin/texrecon
-- Removed runtime path from "/vagrant_data/odm_app/OpenDroneMap/SuperBuild/install/bin/texrecon"
[ 54%] Completed 'mvstexturing'
[ 54%] Built target mvstexturing
make: *** [all] Error 2
Compiling build
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at modules/odm_georef/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "PCL" (requested
  version 1.7) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

 > Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.


>CMake Error at modules/odm_georef/CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

 > Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


>-- Configuring incomplete, errors occurred!
See also "/vagrant_data/odm_app/OpenDroneMap/build/CMakeFiles/CMakeOutput.log".
Configuration Finished
vagrant@vagrant-ubuntu-trusty-64:/vagrant_data/odm_app/OpenDroneMap$

---

Can it be that the download is too slow and the script just continues without waiting on the downloaded file?

**Comment by AZOM** [comment]
Now I tried to pre-download all the dependencies and add them before I start configure.sh
Got the following:

>Performing download step (download, verify and extract) for 'ecto'
[ 57%] -- downloading...
     src='https://github.com/plasmodic/ecto/archive/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip'
     dst='/vagrant_data/odm_app/OpenDroneMap/SuperBuild/download/ecto/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip'
     timeout='none'
Completed 'gflags'
-- Looking for include file stdint.h - found
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Performing Test CGAL_CFG_ISTREAM_INT_BUG - Success
-- Looking for include file sys/types.h
[ 10%] -- Performing Test HAVE_CXX_W - Success
-- Performing Test HAVE_C_W
Building CXX object CMakeFiles/opengv.dir/src/absolute_pose/modules/gpnp1/init.o
-- downloading... done
-- DOXYGEN_FOUND
-- HTML_HELP_COMPILER
[ 57%] Built target gflags
-- verifying file...
     file='/vagrant_data/odm_app/OpenDroneMap/SuperBuild/download/ecto/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip'
-- verifying file... done
-- Found CPack generators: DEB
Scanning dependencies of target ceres
-- extracting...
     src='/vagrant_data/odm_app/OpenDroneMap/SuperBuild/download/ecto/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip'
     dst='/vagrant_data/odm_app/OpenDroneMap/SuperBuild/src/ecto'
-- extracting... [tar xfz]
[ 58%] CMake Error: Problem with archive_write_header(): Can't create 'ecto-c6178ed0102a66cebf503a4213c27b0f60cfca69/doc/kitchen/_static'
CMake Error: Current file: ecto-c6178ed0102a66cebf503a4213c27b0f60cfca69/doc/kitchen/_static
CMake Error: Problem extracting tar: /vagrant_data/odm_app/OpenDroneMap/SuperBuild/download/ecto/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip
-- extracting... [error clean up]
[ 11%] Creating directories for 'ceres'
Building CXX object CMakeFiles/opengv.dir/src/absolute_pose/modules/gpnp1/reductors.o
CMake Error at /vagrant_data/odm_app/OpenDroneMap/SuperBuild/build/ecto/stamp/extract-ecto.cmake:33 (message):
  error: extract of
  '/vagrant_data/odm_app/OpenDroneMap/SuperBuild/download/ecto/c6178ed0102a66cebf503a4213c27b0f60cfca69.zip'
  failed


>make[2]: *** [ecto/stamp/ecto-download] Error 1
make[1]: *** [CMakeFiles/ecto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

---

To me it seems like there could be an issue that the script is trying to open a ".zip" file with `tar xfz` which will hardly work...

---

This is the end of the output:

>Linking CXX shared library ../../lib/libopencv_core.so
CMake Error: cmake_symlink_library: System Error: Protocol error
CMake Error: cmake_symlink_library: System Error: Protocol error
make[5]: *** [lib/libopencv_core.so.2.4.11] Error 1
make[4]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [opencv/stamp/opencv-build] Error 2
make[1]: *** [CMakeFiles/opencv.dir/all] Error 2
make: *** [all] Error 2
Compiling build
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at modules/odm_georef/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "PCL" (requested
  version 1.7) with any of the following names:

>    PCLConfig.cmake
    pcl-config.cmake

>  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

>CMake Error at modules/odm_georef/CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

>    OpenCVConfig.cmake
    opencv-config.cmake

>  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

>-- Configuring incomplete, errors occurred!
See also "/vagrant_data/odm_app/OpenDroneMap/build/CMakeFiles/CMakeOutput.log".
Configuration Finished

**Comment by vidyasagarsmiles** [comment]
Hey Guys,

I am having the same problem ,I tried with the wget option but it is still showing the same error.
Can anyone suggest me a solution for this.

Traceback (most recent call last):
  File "/home/vidyasagarsmiles/src/envmap-187722/ImageStich/OpenDroneMap/run.py", line 8, in <module>
    import ecto
ImportError: No module named ecto

**Comment by dakotabenjamin** [comment]
Please check our [docs](https://docs.opendronemap.org) for installation instructions. We don't support using vagrant anymore.
