### ISSUE TITLE
Stuck on /odm_app/OpenDroneMap/run.pl

### ISSUE THREAD

**Issue by boxerone** [OpenDroneMap/odm_vagrant#8]
HI

I've tried several time to have OpenDroneMap working on windows, but I always get stuck at point 12.
When I run "/odm_app/OpenDroneMap/run.pl I got "no such file or directory"
Any help will be very appreciated

**Comment by smathermather** [comment]
Failed to update the documentation with the latest changes. @dakotabenjamin, I changed document to reflect removal of run.pl. Any other changes needed?
 https://github.com/OpenDroneMap/odm_vagrant/commit/9fdd573863bcd51317c925352414334d4a78cb5e
